import './globals.css'
import MenuNav from '@/components/navigation/MenuNav'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='h-full'>
      <body className='h-full'>
        <nav className='w-full h-[8vh] bg-red-900 '>
          <MenuNav />
        </nav>
        {children}

      </body>
    </html>
  )
}
