import './globals.css'
import MenuNav from '@/components/navigation/MenuNav'
import styles from './layout.module.scss'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`h-full ${styles.body}`}>
        <nav className={`w-full h-[8vh]  flex items-center ${styles.navBar}`}>
          <MenuNav />
        </nav>
        {children}

      </body>
    </html>
  )
}
